spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.106/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.106
    port: 6379
server:
  context-path: /sell
wechat:
  mpAppId: wx8798cfdcbb38d05f
  mpAppSecret: a208c73a01832ed1173b0611f3e4fa7b
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
projectUrl:
  wechatMpAuthorize: http://sell.natapp4.cc
  wechatOpenAuthorize: http://sell.natapp4.cc
logging:
  level:
      com.xf.imti.entity.mapper: trace


